// <auto-generated />
using System;
using API.Infraestructure.Data.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Domain.Entities.ConteudoTrilha", b =>
                {
                    b.Property<string>("IdConteudoTrilha")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_CONTEUDO_TRILHA");

                    b.Property<string>("IdTrilha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_TRILHA");

                    b.Property<string>("NomeConteudoTrilha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME_CONTEUDO_TRILHA");

                    b.Property<string>("TextoConteudoTrilha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TEXTO_CONTEUDO_TRILHA");

                    b.Property<string>("TipoConteudoTrilha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO_CONTEUDO_TRILHA");

                    b.HasKey("IdConteudoTrilha")
                        .HasName("TB_CONTEUDO_TRILHA_ID_CONTEUDO_TRILHA_PK");

                    b.HasIndex("IdTrilha");

                    b.ToTable("TB_CONTEUDO_TRILHA", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.ConteudoTrilhaUsuario", b =>
                {
                    b.Property<string>("IdConteudoTrilhaUsuario")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_CONTEUDO_TRILHA_USUARIO");

                    b.Property<string>("ConteudoTrilhaConcluidaUsuario")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CONTEUDO_TRILHA_CONCLUIDA_USUARIO");

                    b.Property<string>("IdConteudoTrilha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_CONTEUDO_TRILHA");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdConteudoTrilhaUsuario")
                        .HasName("TB_CONTEUDO_TRILHA_USUARIO_ID_CONTEUDO_TRILHA_USUARIO_PK");

                    b.HasIndex("IdConteudoTrilha");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_CONTEUDO_TRILHA_USUARIO", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.EnderecoUsuario", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("CepEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CEP_ENDERECO");

                    b.Property<string>("EstadoEndereco")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ESTADO_ENDERECO");

                    b.Property<string>("LogradouroEndereco")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("LOGRADOURO_ENDERECO");

                    b.HasKey("IdUsuario")
                        .HasName("TB_ENDERECO_USUARIO_ID_USUARIO_PK");

                    b.ToTable("TB_ENDERECO_USUARIO", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.FormularioProfissaoUsuario", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("ProfissaoRecomendada")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PROFISSAO_RECOMENDADA");

                    b.Property<string>("RespostaPergunta1")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESPOSTA_PERGUNTA_1");

                    b.Property<string>("RespostaPergunta10")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESPOSTA_PERGUNTA_10");

                    b.Property<string>("RespostaPergunta2")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESPOSTA_PERGUNTA_2");

                    b.Property<string>("RespostaPergunta3")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESPOSTA_PERGUNTA_3");

                    b.Property<string>("RespostaPergunta4")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESPOSTA_PERGUNTA_4");

                    b.Property<string>("RespostaPergunta5")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESPOSTA_PERGUNTA_5");

                    b.Property<string>("RespostaPergunta6")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESPOSTA_PERGUNTA_6");

                    b.Property<string>("RespostaPergunta7")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESPOSTA_PERGUNTA_7");

                    b.Property<string>("RespostaPergunta8")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESPOSTA_PERGUNTA_8");

                    b.Property<string>("RespostaPergunta9")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESPOSTA_PERGUNTA_9");

                    b.HasKey("IdUsuario")
                        .HasName("TB_FORMULARIO_PROFISSAO_USUARIO_ID_USUARIO_PK");

                    b.ToTable("TB_FORMULARIO_PROFISSAO_USUARIO", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.Trilha", b =>
                {
                    b.Property<string>("IdTrilha")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_TRILHA");

                    b.Property<string>("NomeTrilha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME_TRILHA");

                    b.Property<int>("QuantidadeConteudoTrilha")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTIDADE_CONTEUDO_TRILHA");

                    b.HasKey("IdTrilha")
                        .HasName("TB_TRILHA_ID_TRILHA_PK");

                    b.ToTable("TB_TRILHA", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.TrilhaUsuario", b =>
                {
                    b.Property<string>("IdTrilhaUsuario")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_TRILHA_USUARIO");

                    b.Property<string>("IdTrilha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_TRILHA");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("TrilhaConcluidaUsuario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TRILHA_CONCLUIDA_USUARIO");

                    b.HasKey("IdTrilhaUsuario")
                        .HasName("TB_TRILHA_USUARIO_ID_TRILHA_USUARIO_PK");

                    b.HasIndex("IdTrilha");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_TRILHA_USUARIO", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.Usuario", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<DateTime>("DataNascimentoUsuario")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO_USUARIO");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL_USUARIO");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME_USUARIO");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SENHA_USUARIO");

                    b.HasKey("IdUsuario")
                        .HasName("TB_USUARIO_ID_USUARIO_PK");

                    b.ToTable("TB_USUARIO", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.ConteudoTrilha", b =>
                {
                    b.HasOne("API.Domain.Entities.Trilha", "Trilha")
                        .WithMany("ConteudosTrilha")
                        .HasForeignKey("IdTrilha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trilha");
                });

            modelBuilder.Entity("API.Domain.Entities.ConteudoTrilhaUsuario", b =>
                {
                    b.HasOne("API.Domain.Entities.ConteudoTrilha", "ConteudoTrilha")
                        .WithMany("ConteudosUsuarios")
                        .HasForeignKey("IdConteudoTrilha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ConteudosTrilhaUsuario")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConteudoTrilha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API.Domain.Entities.EnderecoUsuario", b =>
                {
                    b.HasOne("API.Domain.Entities.Usuario", "Usuario")
                        .WithOne("EnderecoUsuario")
                        .HasForeignKey("API.Domain.Entities.EnderecoUsuario", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API.Domain.Entities.FormularioProfissaoUsuario", b =>
                {
                    b.HasOne("API.Domain.Entities.Usuario", "Usuario")
                        .WithOne("FormularioProfissaoUsuario")
                        .HasForeignKey("API.Domain.Entities.FormularioProfissaoUsuario", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API.Domain.Entities.TrilhaUsuario", b =>
                {
                    b.HasOne("API.Domain.Entities.Trilha", "Trilha")
                        .WithMany("TrilhasUsuario")
                        .HasForeignKey("IdTrilha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.Entities.Usuario", "Usuario")
                        .WithMany("TrilhasUsuario")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trilha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API.Domain.Entities.ConteudoTrilha", b =>
                {
                    b.Navigation("ConteudosUsuarios");
                });

            modelBuilder.Entity("API.Domain.Entities.Trilha", b =>
                {
                    b.Navigation("ConteudosTrilha");

                    b.Navigation("TrilhasUsuario");
                });

            modelBuilder.Entity("API.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ConteudosTrilhaUsuario");

                    b.Navigation("EnderecoUsuario");

                    b.Navigation("FormularioProfissaoUsuario");

                    b.Navigation("TrilhasUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
